version: '2'
services:
    seat_api:
        build: .
        container_name: seat_api
        hostname: seat_api
        restart: always
        ports:
          - 9487:8000
        environment:
          - host=redis
          - port=6379
          - CONTRIB_SERVICE_NAME=seat_api
          - CONTRIB_JAEGER_HOST=192.168.30.127
          - CONTRIB_JAEGER_PORT=6831
    redis:
        image: redis:6.0-alpine
        container_name: redis
        hostname: redis
        ports:
          - 6379:6379
